# nameserver host
nameserver_host: n20.playground.id

# nameserver port
nameserver_port: 8080

# blocksize in mb
blocksize: 1

# datanode port
datanode_port: 3000

# datanode host list
datanode_host :
  - n20.playground.id
  - n21.playground.id
